/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Mod = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'version' : IDL.Text,
  'enabled' : IDL.Bool,
  'jsonContent' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMod' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteMod' : IDL.Func([IDL.Text], [], []),
  'getMod' : IDL.Func([IDL.Text], [Mod], ['query']),
  'listMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
  'toggleModEnabled' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Mod = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'version' : IDL.Text,
    'enabled' : IDL.Bool,
    'jsonContent' : IDL.Text,
  });
  
  return IDL.Service({
    'addMod' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteMod' : IDL.Func([IDL.Text], [], []),
    'getMod' : IDL.Func([IDL.Text], [Mod], ['query']),
    'listMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
    'toggleModEnabled' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };